name: Ubuntu

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'true'
jobs:
  Ubuntu:
    runs-on: ubuntu-20.04
    
    steps:
    - name: Setup Debug Session
      uses: csexton/debugger-action@master
